<? /*
<module>
    <modulename>comments</modulename>
    <version>1.0</version>
    <revision>0</revision>
    <description>The comments module, this is a core module, installed by default.</description>
    <core>yes</core>
    <installed>no</installed>
    <enabled>no</enabled>
    <search>no</search>
    <dependancy>
    </dependancy>
    <models>
        <model>
            <name>Comments_Comment</name>
            <permissions>
                <permission>retractall</permission>
                <permission>retract</permission>
                <permission>showall</permission>
                <permission>show</permission>
                <permission>list</permission>
                <permission>delete</permission>
                <permission>new</permission>
                <export>comments-add</export>
                <export>comments-retract</export>
                <export>comments-show</export>
                <export>comments-edit</export>
                <export>comments-remove</export>
            </permissions>
            <relationships>
			    <relationship>creator</relationship>
			</relationships>
        </model>
    </models>
    <defaultpermissions>
		student:p|comments|comments_comment|show
		student:p|comments|comments_comment|showall
		student:c|comments|comments_comment|retract|(if)|creator
		teacher:p|comments|comments_comment|show
		teacher:p|comments|comments_comment|showall
		teacher:c|comments|comments_comment|retract|(if)|creator
    </defaultpermissions>
    <blocks>
    </blocks>
</module>
*/ ?>
