<? /*
<module>
    <modulename>forums</modulename>
    <version>1.0</version>
    <revision>0</revision>
    <description>School and general forums.</description>
    <core>no</core>
    <installed>no</installed>
    <enabled>yes</enabled>
    <search>no</search>
    <dependencies>
        <module>aliases</module>
        <module>images</module>
    </dependencies>
    <models>
      <model>
        <name>forums_board</name>
		<description>A space in which to create and discuss topics (threads).</description>
        <permissions>
          <permission>new</permission>
          <permission>show</permission>
          <permission>edit</permission>
          <permission>delete</permission>
        </permissions>
        <relationships>
		  <relationship>creator</relationship>
		  <relationship>poster</relationship>
		  <relationship>moderator</relationship>
        </relationships>
      </model>
      <model>
        <name>forums_thread</name>
		<description>A thread of discussion on a board.</description>
        <permissions>
          <permission>new</permission>
          <permission>show</permission>
          <permission>edit</permission>
          <permission>delete</permission>
        </permissions>
        <relationships>
		  <relationship>creator</relationship>
		  <relationship>poster</relationship>
		  <relationship>moderator</relationship>
        </relationships>
      </model>
      <model>
        <name>forums_reply</name>
		<description>A thread of discussion on a board.</description>
        <permissions>
          <permission>new</permission>
          <permission>show</permission>
          <permission>edit</permission>
          <permission>delete</permission>
        </permissions>
        <relationships>
		  <relationship>creator</relationship>
		  <relationship>poster</relationship>
		  <relationship>moderator</relationship>
        </relationships>
      </model>
	</models>
    <defaultpermissions>
		student:p|forums|forums_board|show
		student:p|forums|forums_board|makethread
		student:p|forums|forums_thread|show
		student:p|forums|forums_thread|new
		student:p|forums|forums_reply|show
		student:p|forums|forums_reply|new
		student:p|forums|forums_board|images-list
		student:p|forums|forums_board|images-show
		student:p|forums|forums_board|images-list

		teacher:p|forums|forums_board|show
		teacher:p|forums|forums_board|makethread
		teacher:p|forums|forums_board|new
		teacher:c|forums|forums_board|edit|(if)|creator
		teacher:c|forums|forums_board|delete|(if)|creator
		teacher:p|forums|forums_board|images-add
		teacher:p|forums|forums_board|images-show
		teacher:p|forums|forums_board|images-list

		teacher:p|forums|forums_thread|show
		teacher:p|forums|forums_thread|new
		teacher:c|forums|forums_thread|images-add|(if)|creator
		teacher:p|forums|forums_thread|images-show
		teacher:p|forums|forums_thread|images-list
		teacher:p|forums|forums_reply|show
		teacher:p|forums|forums_reply|new
		teacher:c|forums|forums_reply|images-add|(if)|creator
		teacher:p|forums|forums_reply|images-show
		teacher:p|forums|forums_reply|images-list
    </defaultpermissions>
</module>
*/ ?>
